### ISSUE TITLE
how to export to ONNX model?

### ISSUE THREAD

**Issue by 1191658517** [lyakaap/ISC21-Descriptor-Track-1st#11]
when i use this code to export ONNX Model:

import requests
import torch
from PIL import Image

from isc_feature_extractor import create_model

recommended_weight_name = 'isc_ft_v107'
model, preprocessor = create_model(weight_name=recommended_weight_name, device='cpu')

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
x = preprocessor(image).unsqueeze(0)
input_name = 'input'
output_name = 'output'

torch.onnx.export(model,    
                  x,              
                  'model.onnx',      
                  input_names=['input'],     
                  output_names=['output'], 
                  opset_version=11,       
               )
y = model(x)
print(y.shape)  # => torch.Size([1, 256])

It has the following error：RuntimeError: Failed to export an ONNX attribute 'onnx::Squeeze', since it's not constant, please try to make things (e.g., kernel size) static if possible

can you tell me how to export a ONNX model Correctly？thank you!

**Comment by 1191658517** [comment]
报错torch.onnx.errors.SymbolicValueError: Failed to export a node '%2496 : Long(device=cpu) = onnx::Squeeze[axes=[0]](%2495), scope: isc_feature_extractor.model.ISCNet:: # /media/aimall/70f1ac87-9fa9-4ab1-bb71-dd9de896f0eb/home/aimall/github1/ISC21-Descriptor-Track-1st/isc_feature_extractor/model.py:72:0
' (in list node %2505 : int[] = prim::ListConstruct(%2496, %2504), scope: isc_feature_extractor.model.ISCNet::
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2505 defined in (%2505 : int[] = prim::ListConstruct(%2496, %2504), scope: isc_feature_extractor.model.ISCNet::
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 
    Inputs:
        #0: 2496 defined in (%2496 : Long(device=cpu) = onnx::Squeeze[axes=[0]](%2495), scope: isc_feature_extractor.model.ISCNet:: # /media/aimall/70f1ac87-9fa9-4ab1-bb71-dd9de896f0eb/home/aimall/github1/ISC21-Descriptor-Track-1st/isc_feature_extractor/model.py:72:0
    )  (type 'Tensor')
        #1: 2504 defined in (%2504 : Long(device=cpu) = onnx::Squeeze[axes=[0]](%2503), scope: isc_feature_extractor.model.ISCNet:: # /media/aimall/70f1ac87-9fa9-4ab1-bb71-dd9de896f0eb/home/aimall/github1/ISC21-Descriptor-Track-1st/isc_feature_extractor/model.py:72:0
    )  (type 'Tensor')
    Outputs:
        #0: 2505 defined in (%2505 : int[] = prim::ListConstruct(%2496, %2504), scope: isc_feature_extractor.model.ISCNet::
    )  (type 'List[int]')

**Comment by minsoo-jeong** [comment]
I have the same problem. Have you solved it?
