### ISSUE TITLE
will v107 overfit for phase2?

### ISSUE THREAD

**Issue by liangzimei** [lyakaap/ISC21-Descriptor-Track-1st#2]
Congratulations  and thanks for your sharing.

i find v107 only  use the  about 5k query-ref pair (i.e. gt in phase1) as positive. How to know whether it  overfits for phase2 ?

**Comment by lyakaap** [comment]
Actually, there is no way to assess overfitting, as ground-truth of phase-2 are not disclosed.
During the competition period, I compared several models by the copy detection result by eye-checking locally, and selected the model which shows most reasonable output.
