### ISSUE TITLE
data augment is wrong

### ISSUE THREAD

**Issue by AItechnology** [lyakaap/ISC21-Descriptor-Track-1st#3]
train_dataset = ISCDataset(
        train_paths,
        NCropsTransform(
            transforms.Compose(aug_moderate),
            transforms.Compose(aug_hard),
            args.ncrops,
        ),
    )

error log: apply_transform() takes from 2 to 3 positional arguments but 5 were given

**Comment by lyakaap** [comment]
Could you give me more context?
How was the argument options?

**Comment by AItechnology** [comment]
I found the problem

**Comment by lyakaap** [comment]
I'm not sure why it happens. Have you checked your python libraries's version?
Maybe I can make the answer If you paste entire error message here instead of screenshot.

**Comment by AItechnology** [comment]
![image](https://user-images.githubusercontent.com/19428141/146765161-77801f54-ea77-4567-9632-0ef0ff4ad102.png)

**Comment by Usernamezhx** [comment]
@AItechnology I think it is a augly version problem. you can **pip install augly==0.1.2** that can be solved.
