### ISSUE TITLE
about the memory size

### ISSUE THREAD

**Issue by Usernamezhx** [lyakaap/ISC21-Descriptor-Track-1st#4]
```python
python v107.py \
  -a tf_efficientnetv2_m_in21ft1k --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 --seed 99999 \
  --epochs 10 --lr 0.5 --wd 1e-6 \
  --gem-p 1.0 --pos-margin 0.0 --neg-margin 1.1 --weight ./v98/train/checkpoint_0001.pth.tar \
  --input-size 512 --sample-size 1000000 --memory-size 1000 \
  ../input/training_images/
```
why not set the **--memory-size** large such as 20000 ? thanks in advance

**Comment by lyakaap** [comment]
In v107.py, ground truth pairs are used for training and the number of these are only around few thousands. The reason why I set memory size smaller than the others is that setting memory size to 20000 is too large compared to the samples used for training.
