### ISSUE TITLE
Cannot load state dict for model

### ISSUE THREAD

**Issue by NguyenThanhAI** [lyakaap/ISC21-Descriptor-Track-1st#6]
Thanks for your amazing work. But I encounter a problem, when I use ```checkpoint_0009.pth.tar``` checkpoint,
- When I don't remove ```model = nn.DataParallel(model)```, I encouter error:

```RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.backbone.bn1.weight: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is 
torch.Size([64]).
        size mismatch for module.backbone.bn1.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.bn1.running_mean: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.bn1.running_var: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.fc.weight: copying a param with shape torch.Size([256, 512]) from checkpoint, the shape in current model is torch.Size([256, 2048])
```

- Then I remove line ```model = nn.DataParallel(model)```, the model seems to load checkpoint successfully, but I feed same input to model, the output feature vector if different for different time I run. I guess the model is not loaded successfully when load state dict, so model will use the weight initialized randomly.
- Then I change ```strict=True``` in ```model.load_state_dict(state_dict=state_dict, strict=False)```,  I encounter error ```RuntimeError: Error(s) in loading state_dict for ISCNet:
        Missing key(s) in state_dict:```, I found that the key of state_dict in model and checkpoint totally diffrent even name pattern. Key of model state dict and checkpoint state dict I attached below.
[checkpoint.txt](https://github.com/lyakaap/ISC21-Descriptor-Track-1st/files/8527346/checkpoint.txt)
[model.txt](https://github.com/lyakaap/ISC21-Descriptor-Track-1st/files/8527347/model.txt)
How can I solve the this problem?

**Comment by lyakaap** [comment]
I guess you changed some parameters related to model definition. If you do so, model architecture doesn't match the architecture which checkpoint file assumes, and fails to load checkpoint properly.
Would you check if you can load checkpoints properly with default settings (shown below) on your environment?
```
cd exp

python v107.py -a tf_efficientnetv2_m_in21ft1k --batch-size 128 --mode extract --gem-eval-p 1.0 --weight ./v107/train/checkpoint_0009.pth.tar --input-size 512 --target-set qrt ../input/
```

**Comment by NguyenThanhAI** [comment]
I solved my issue, I just typed wrong architecture of backbone ,thanks for your work :D
