### ISSUE TITLE
Unable to reproduce Stage 1 results

### ISSUE THREAD

**Issue by avrilwongaw** [lyakaap/ISC21-Descriptor-Track-1st#8]
Hi, I attempted to reproduce the Stage 1 training using your provided code, but was unable to obtain the reported muAP of 0.5831. I instead obtained this result at epoch 9 (indexed from 0):
```
Average Precision: 0.49554
Recall at P90    : 0.32701
Threshold at P90 : -0.375733
Recall at rank 1:  0.62448
Recall at rank 10: 0.65961
```

I also saw that you continued training from epoch 5, but these are the results I obtained at epoch 5:
```
Average Precision: 0.47977
Recall at P90    : 0.32501
Threshold at P90 : -0.376619
Recall at rank 1:  0.61409
Recall at rank 10: 0.64903
```

Both sets of results were obtained on the private ground truth set of Phase 1, using image size 512. Is it possible to provide some insight as to what is happening here? Thank you.

**Comment by zc277584121** [comment]
image size should be 256 in Stage 1 according to the paper.
